package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"time"

	"github.com/chris/coworker/core"
)

// WorkerStore manages the workers table: registration, heartbeat, and eviction.
type WorkerStore struct {
	db    *DB
	event *EventStore
}

// NewWorkerStore creates a WorkerStore.
func NewWorkerStore(db *DB, event *EventStore) *WorkerStore {
	return &WorkerStore{db: db, event: event}
}

// Register inserts a new live worker row and emits a worker.registered event.
// The handle is caller-supplied (generated by the MCP handler via core.NewID()).
func (s *WorkerStore) Register(ctx context.Context, w *core.Worker) error {
	now := w.RegisteredAt
	if now.IsZero() {
		now = time.Now()
		w.RegisteredAt = now
	}
	w.LastHeartbeat = now
	w.State = core.WorkerStateLive

	payload, err := json.Marshal(map[string]interface{}{
		"handle":     w.Handle,
		"role":       w.Role,
		"pid":        w.PID,
		"session_id": w.SessionID,
		"cli":        w.CLI,
	})
	if err != nil {
		return fmt.Errorf("marshal worker.registered payload: %w", err)
	}

	// Worker events are not run-scoped; run_id is left empty (stored as NULL).
	event := &core.Event{
		ID:            core.NewID(),
		RunID:         "",
		Kind:          core.EventWorkerRegistered,
		SchemaVersion: 1,
		CorrelationID: w.Handle,
		Payload:       string(payload),
		CreatedAt:     now,
	}

	return s.event.WriteEventThenRow(ctx, event, func(tx *sql.Tx) error {
		_, err := tx.ExecContext(ctx,
			`INSERT INTO workers
				(handle, role, pid, session_id, cli, registered_at, last_heartbeat_at, state)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
			w.Handle, w.Role, w.PID, w.SessionID, w.CLI,
			now.UTC().Format(time.RFC3339),
			now.UTC().Format(time.RFC3339),
			string(w.State),
		)
		return err
	})
}

// Heartbeat updates last_heartbeat_at to now and emits a worker.heartbeat event.
// Returns an error if the handle is not found or the worker is not live.
func (s *WorkerStore) Heartbeat(ctx context.Context, handle string) error {
	now := time.Now()

	payload, err := json.Marshal(map[string]string{
		"handle": handle,
	})
	if err != nil {
		return fmt.Errorf("marshal worker.heartbeat payload: %w", err)
	}

	event := &core.Event{
		ID:            core.NewID(),
		RunID:         "",
		Kind:          core.EventWorkerHeartbeat,
		SchemaVersion: 1,
		CorrelationID: handle,
		Payload:       string(payload),
		CreatedAt:     now,
	}

	return s.event.WriteEventThenRow(ctx, event, func(tx *sql.Tx) error {
		result, err := tx.ExecContext(ctx,
			`UPDATE workers SET last_heartbeat_at = ?, state = 'live'
			WHERE handle = ? AND state != 'evicted'`,
			now.UTC().Format(time.RFC3339), handle,
		)
		if err != nil {
			return err
		}
		n, err := result.RowsAffected()
		if err != nil {
			return fmt.Errorf("rows affected: %w", err)
		}
		if n == 0 {
			return fmt.Errorf("worker %q not found or already evicted", handle)
		}
		return nil
	})
}

// Deregister marks a worker as evicted (clean shutdown) and emits a
// worker.deregistered event. Leased dispatches for the handle are NOT
// automatically requeued here — that is the watchdog's responsibility
// (and it handles deregistered workers the same as evicted ones).
func (s *WorkerStore) Deregister(ctx context.Context, handle string) error {
	now := time.Now()

	payload, err := json.Marshal(map[string]string{
		"handle": handle,
	})
	if err != nil {
		return fmt.Errorf("marshal worker.deregistered payload: %w", err)
	}

	event := &core.Event{
		ID:            core.NewID(),
		RunID:         "",
		Kind:          core.EventWorkerDeregistered,
		SchemaVersion: 1,
		CorrelationID: handle,
		Payload:       string(payload),
		CreatedAt:     now,
	}

	return s.event.WriteEventThenRow(ctx, event, func(tx *sql.Tx) error {
		result, err := tx.ExecContext(ctx,
			`UPDATE workers SET state = 'evicted'
			WHERE handle = ? AND state != 'evicted'`,
			handle,
		)
		if err != nil {
			return err
		}
		n, err := result.RowsAffected()
		if err != nil {
			return fmt.Errorf("rows affected: %w", err)
		}
		if n == 0 {
			return fmt.Errorf("worker %q not found or already evicted", handle)
		}
		return nil
	})
}

// LiveWorkersForRole returns all workers in state 'live' for the given role,
// ordered by registered_at ascending (oldest first = primary worker).
func (s *WorkerStore) LiveWorkersForRole(ctx context.Context, role string) ([]core.Worker, error) {
	rows, err := s.db.QueryContext(ctx,
		`SELECT handle, role, pid, session_id, cli, registered_at, last_heartbeat_at, state
		FROM workers
		WHERE role = ? AND state = 'live'
		ORDER BY registered_at ASC`,
		role,
	)
	if err != nil {
		return nil, fmt.Errorf("query live workers: %w", err)
	}
	defer rows.Close()

	var workers []core.Worker
	for rows.Next() {
		var w core.Worker
		var regAt, hbAt, stateStr string
		if err := rows.Scan(
			&w.Handle, &w.Role, &w.PID, &w.SessionID, &w.CLI,
			&regAt, &hbAt, &stateStr,
		); err != nil {
			return nil, fmt.Errorf("scan worker: %w", err)
		}
		w.RegisteredAt, _ = time.Parse(time.RFC3339, regAt)
		w.LastHeartbeat, _ = time.Parse(time.RFC3339, hbAt)
		w.State = core.WorkerState(stateStr)
		workers = append(workers, w)
	}
	return workers, rows.Err()
}

// MarkStale transitions all live workers whose last_heartbeat_at is older than
// cutoff to state 'stale'. Returns the handles of newly-stale workers.
func (s *WorkerStore) MarkStale(ctx context.Context, cutoff time.Time) ([]string, error) {
	cutoffStr := cutoff.UTC().Format(time.RFC3339)

	rows, err := s.db.QueryContext(ctx,
		`SELECT handle FROM workers
		WHERE state = 'live' AND last_heartbeat_at < ?`,
		cutoffStr,
	)
	if err != nil {
		return nil, fmt.Errorf("query stale candidates: %w", err)
	}
	defer rows.Close()

	var handles []string
	for rows.Next() {
		var h string
		if err := rows.Scan(&h); err != nil {
			return nil, fmt.Errorf("scan handle: %w", err)
		}
		handles = append(handles, h)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	if len(handles) == 0 {
		return nil, nil
	}

	// Bulk update without individual events — the watchdog emits a single
	// eviction event per handle in its own loop.
	_, err = s.db.ExecContext(ctx,
		`UPDATE workers SET state = 'stale'
		WHERE state = 'live' AND last_heartbeat_at < ?`,
		cutoffStr,
	)
	if err != nil {
		return nil, fmt.Errorf("mark stale: %w", err)
	}

	return handles, nil
}

// MarkEvicted transitions stale workers with last_heartbeat_at older than
// cutoff to state 'evicted' and emits a worker.deregistered event for each.
// Returns the handles of newly-evicted workers so the caller can requeue
// their leased dispatches.
func (s *WorkerStore) MarkEvicted(ctx context.Context, cutoff time.Time) ([]string, error) {
	cutoffStr := cutoff.UTC().Format(time.RFC3339)

	rows, err := s.db.QueryContext(ctx,
		`SELECT handle FROM workers
		WHERE state = 'stale' AND last_heartbeat_at < ?`,
		cutoffStr,
	)
	if err != nil {
		return nil, fmt.Errorf("query eviction candidates: %w", err)
	}
	defer rows.Close()

	var handles []string
	for rows.Next() {
		var h string
		if err := rows.Scan(&h); err != nil {
			return nil, fmt.Errorf("scan handle: %w", err)
		}
		handles = append(handles, h)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	now := time.Now()
	for _, h := range handles {
		payload, _ := json.Marshal(map[string]string{"handle": h, "reason": "heartbeat_timeout"})
		event := &core.Event{
			ID:            core.NewID(),
			RunID:         "",
			Kind:          core.EventWorkerDeregistered,
			SchemaVersion: 1,
			CorrelationID: h,
			Payload:       string(payload),
			CreatedAt:     now,
		}
		handle := h // capture
		if err := s.event.WriteEventThenRow(ctx, event, func(tx *sql.Tx) error {
			_, err := tx.ExecContext(ctx,
				`UPDATE workers SET state = 'evicted'
				WHERE handle = ? AND state = 'stale'`,
				handle,
			)
			return err
		}); err != nil {
			return nil, fmt.Errorf("evict worker %q: %w", h, err)
		}
	}

	return handles, nil
}

// GetWorker retrieves a worker by handle. Returns nil if not found.
func (s *WorkerStore) GetWorker(ctx context.Context, handle string) (*core.Worker, error) {
	var w core.Worker
	var regAt, hbAt, stateStr string

	err := s.db.QueryRowContext(ctx,
		`SELECT handle, role, pid, session_id, cli, registered_at, last_heartbeat_at, state
		FROM workers WHERE handle = ?`,
		handle,
	).Scan(&w.Handle, &w.Role, &w.PID, &w.SessionID, &w.CLI, &regAt, &hbAt, &stateStr)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("get worker %q: %w", handle, err)
	}

	w.RegisteredAt, _ = time.Parse(time.RFC3339, regAt)
	w.LastHeartbeat, _ = time.Parse(time.RFC3339, hbAt)
	w.State = core.WorkerState(stateStr)
	return &w, nil
}

// RequeueLeasedDispatches resets all dispatches leased by the given worker
// handle to 'pending' and emits dispatch.expired events for each.
// Called by the watchdog immediately after MarkEvicted.
func (s *WorkerStore) RequeueLeasedDispatches(ctx context.Context, handle string, ds *DispatchStore) error {
	return ds.RequeueByWorker(ctx, handle)
}
